### ISSUE TITLE
Elytra Wont Fly

### ISSUE THREAD

**Issue by Kissune** [MJRLegends/Space-Astronomy-2-Feedback-#128]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** 
Yes
### Description of Issue
Elytra doesnt fly

### Steps to Reproduce Issue
1. Equip Elytra
2. Attempt to fly

**Crash log/Log (if applicable):** 
**Screenshots (if applicable):** 

**Version of Mod Pack using:** 1.3.0

**Where did this bug happen:** 
Tested on both single player and server

**Comment by MJRLegends** [comment]
Im unable to reproduce this, on a server they might not work 100% due to vanilla minecraft, and you need to be in survival only. Also things like jetpacks and creative fly or/and anything that makes you fly or jetpack on space bar press will stop it happening

See https://gyazo.com/b076240cc188b73f99bdf67258d7ed49 for my test on this using MC 1.3.0

**Comment by MJRLegends** [comment]
Thanks for the bug report though :D
