### ISSUE TITLE
Issues with the Tiny Progressions Growth Crystals times

### ISSUE THREAD

**Issue by akimbaev** [MJRLegends/Space-Astronomy-2-Feedback-#72]
### ---Issue Report---
**Have you checked Open/Closed Issues (if applicable & PLEASE CHECK BEFORE POSTING):** [Yes or No]
Yes

### Description of Issue
hello, growth crystal tier 3 (tiny progressions) it doesn't work and tier 2 too don't work . what we did
wrong ?

### Steps to Reproduce Issue
1. Take Growth crystal tier 3
2. and it doesn't work

**Crash log/Log (if applicable):** [PASTEBIN. Do NOT copy and paste the log into the issue post itself.]
Nope

**Screenshots (if applicable):** 
![2017-08-02_03 33 33](https://user-images.githubusercontent.com/30404027/28848147-b69d7a34-7733-11e7-99ab-dd4eb7a1671a.png)

**Version of Mod Pack using:** [VERSION]
1.2.1
**Where did this bug happen:** [Single Player or Server]
Single Player(local game)
### Additional Information
[Any other information that may be able to help me with the problem]
Help pls )

**Comment by MJRLegends** [comment]
Whats not working about it?

**Comment by akimbaev** [comment]
Essence doesn't growth faster

**Comment by MJRLegends** [comment]
They increase the time it takes. and dont increase it to be 2 seconds, and they probably dont work as the essences are probably locked to a certain possible speed. Mystical Agriculture has its own Growth Accelerators

**Comment by akimbaev** [comment]
but i had seen a video how work with Mystical Agriculture

**Comment by akimbaev** [comment]
but also default seeds isn't working

**Comment by MJRLegends** [comment]
Ok i just tested it myself and it works fine, they are not meant to be super super fast just a small increase each time

**Comment by MJRLegends** [comment]
But i have check the code and tested multiple times and i can prove they do work :D

**Comment by MJRLegends** [comment]
Looking at it again, i think something is up, let me triple check

**Comment by MJRLegends** [comment]
Thank will be fixed in the update later this week

**Comment by MJRLegends** [comment]
Sorry for the confusion :D

**Comment by MJRLegends** [comment]
Ok the bug seems to be the Tier 2 is faster more than the Tier 3 but there is a speed in increase from the Tier 1 to 2/3

Speeds are as follow

Tier 1: Number of Ticks between Growth Ticks = 4000
Tier 2: Number of Ticks between Growth Ticks = 200
Tier 3: Number of Ticks between Growth Ticks = 300

So there is a bug here yeah but not one due to the fact of Tier 1 is more faster than Tier 2 or Tier 3

I will be making them the following
Tier 1: Number of Ticks between Growth Ticks = 1200
Tier 2: Number of Ticks between Growth Ticks = 400
Tier 3: Number of Ticks between Growth Ticks = 300

**Comment by MJRLegends** [comment]
Ok the bug seems to be the Tier 2 is faster more than the Tier 3 but there is a speed in increase from the Tier 1 to 2/3

**Speeds are as follow**

Tier 1: Number of Ticks between Growth Ticks = 4000
Tier 2: Number of Ticks between Growth Ticks = 200
Tier 3: Number of Ticks between Growth Ticks = 300

**So there is a bug here yeah but not one due to the fact of Tier 1 is more faster than Tier 2 or Tier 3**

**I will be making them the following**
Tier 1: Number of Ticks between Growth Ticks = 1600
Tier 2: Number of Ticks between Growth Ticks = 800
Tier 3: Number of Ticks between Growth Ticks = 300

**Comment by MJRLegends** [comment]
Thanks for reporting though i will get the above changes made, any more issues please let me know :D
